name: Upload Anaconda Cloud

on: workflow_dispatch
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
      - name: Install dependencies
        run: |
            conda install anaconda-client 
            shell: bash -l {0}
            anaconda upload condaDist/noarch/mpl_qt_viz*
